language: cpp
compiler: gcc
sudo: required

stages:
- install
- build
- test
- deploy

install:
- sudo apt-get install -qq qt5-qmake qtbase5-dev

build:
- qmake
- make

test:
- echo test

deploy:
  provider: releases
  api_key:
    secure: rItks+7IkNVcAowkKCrw6qjb3tysQxrN8hJLLZG/ID245UWDEH0qUa5FJZA+ZXEE54A2rgD3SsQwCwxhyC8snDRDB8WcUrFV4B7sXuYVT2FsjqGVNQ8h5bnPgB1FrVgpzuYAuCLx5KlVK6O2Gg/gmPY6wH/iVQobBttcFnpueAjtkuo4bcaJoP5e0FMZ+BRNImMSwtBsP4Be9PrUO8t2lcYxSgRMUpNxj6Lw9/Gh10GhmMdLI79abzM75RMaQyLMz3tgE5A2H8vh7QI1XbcAMFn/jg4n3YL2QvIwso2gQTdpboOjcv7Kx3dDIk/sc4ehOcSUMaX7WWYlVKx005QexHJc1LmgiSMBmlxRa8z92Id4MyRpo+gKZRtu9NKv8s26BeiEaENnmSnpAG4bcd+apA1Y4l+DhX3yd9Vf9IapWXKqlUyNoj67fIUH+C2Sl2WnT5U63bPeZ6A1xSz/VqacIye5Az6fEGi2I1th1kANqpw6J9q3SiQj4uiUlzFqoQVYrkzFXm4WOvBh5N/VOtCQyOcwjhOWTqGLsnVSuOJgJPls+EpKqJF11DvNsFO6DUm9QJMB4wXjxXhHHvVz6ETzaD7rMiyYD4B2k2BdQ0Sm/E2PDXR09sTdNymEN1sFLKxP+zE0jXSNYsOuz1gqQzzL+6I95aNcq7eKepArNKtb5mc=
  file: app
  skip_cleanup: true
  on:
    tags: true